name: Docker Image CI

on:
  push:
    branches: [ "server" ]
  pull_request:
    branches: [ "server" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    - name: Checkout

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      env:
        IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/musikatserver
      run: |
        docker build -t $IMAGE_NAME:latest .
        docker push $IMAGE_NAME:latest
